-- Set kvkk_consent_at to be generated by the database (server-side clock).
-- Prevents clients from spoofing the consent timestamp.
ALTER TABLE public.efep_registrations
  ALTER COLUMN kvkk_consent_at SET DEFAULT now();
